name: 'Release Please 🏭'
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 🤠 Checkout salesforce-actions
        uses: actions/checkout@v4
        with:
          repository: victor-wang-anz/private-actions
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.actions
      - name: Run Release Please
        uses: ./.actions/release-please-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          target-branch: main
